version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: thiphamngoc/banhang-backend:latest
    container_name: banhang-backend
    restart: always
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - DATABASE=mongodb://mongo:27017/banhangdb
    command: ["npm", "start"]

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: banhang-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mongo_data:
